from __future__ import annotations

import json
import re
from typing import Any

from app.models.ai import AIAnalysis
from app.models.enums import FindingClass
from app.models.study import Study


ReportLang = str


def normalize_report_lang(lang: str | None) -> ReportLang:
    value = (lang or "ru").strip().lower()
    if value.startswith("kk"):
        return "kk"
    if value.startswith("en"):
        return "en"
    return "ru"


TEXT = {
    "kk": {
        "draft_title": "AI қорытынды жобасы",
        "study": "Зерттеу",
        "patient": "Пациент коды",
        "study_type": "Зерттеу түрі",
        "clinical_note": "Клиникалық жазба",
        "ai_class": "AI алдын ала диагнозы",
        "confidence": "AI сенімділігі",
        "findings": "Сипаттама",
        "impression": "Қорытынды",
        "recommendations": "Ұсыныстар",
        "no_analysis": "AI талдау аяқталмаған немесе қолжетімсіз.",
        "low_confidence": "AI сенімділігі белгіленген шектен төмен. Диагностикалық класс жасырылды.",
        "doctor_review": "Соңғы қорытындыны дәрігер суретпен және клиникалық деректермен салыстырып растауы керек.",
        "model_note": "Бұл мәтін AI таңдаған құрылымдық класс бойынша MedAI шаблонымен жасалды.",
    },
    "ru": {
        "draft_title": "AI-черновик заключения",
        "study": "Исследование",
        "patient": "Код пациента",
        "study_type": "Тип исследования",
        "clinical_note": "Клиническая заметка",
        "ai_class": "Предварительный AI-диагноз",
        "confidence": "Уверенность AI",
        "findings": "Описание",
        "impression": "Заключение",
        "recommendations": "Рекомендации",
        "no_analysis": "AI-анализ не завершен или недоступен.",
        "low_confidence": "Уверенность AI ниже заданного порога. Диагностический класс скрыт.",
        "doctor_review": "Финальное заключение врач должен сверить со снимком и клиническими данными.",
        "model_note": "Текст сформирован MedAI по структурному классу, выбранному AI.",
    },
    "en": {
        "draft_title": "AI report draft",
        "study": "Study",
        "patient": "Patient code",
        "study_type": "Study type",
        "clinical_note": "Clinical note",
        "ai_class": "Preliminary AI diagnosis",
        "confidence": "AI confidence",
        "findings": "Findings",
        "impression": "Impression",
        "recommendations": "Recommendations",
        "no_analysis": "AI analysis has not been completed or is unavailable.",
        "low_confidence": "AI confidence is below the configured threshold. The diagnostic class is hidden.",
        "doctor_review": "The final report must be checked against the image and clinical data by a clinician.",
        "model_note": "This text was generated by MedAI from the structured class selected by AI.",
    },
}


FINDING_LABELS = {
    "kk": {
        FindingClass.normal: "Норма",
        FindingClass.pneumonia: "Пневмония",
        FindingClass.pleural_effusion: "Плевралық сұйықтық",
        FindingClass.pneumothorax: "Пневмоторакс",
        FindingClass.atelectasis: "Ателектаз",
    },
    "ru": {
        FindingClass.normal: "Норма",
        FindingClass.pneumonia: "Пневмония",
        FindingClass.pleural_effusion: "Плевральный выпот",
        FindingClass.pneumothorax: "Пневмоторакс",
        FindingClass.atelectasis: "Ателектаз",
    },
    "en": {
        FindingClass.normal: "Normal",
        FindingClass.pneumonia: "Pneumonia",
        FindingClass.pleural_effusion: "Pleural effusion",
        FindingClass.pneumothorax: "Pneumothorax",
        FindingClass.atelectasis: "Atelectasis",
    },
}


FINDING_TEXT = {
    "kk": {
        FindingClass.normal: {
            "findings": "Айқын жедел кардиопульмоналды өзгерістер анықталмайды. Өкпе алаңдары айқын, плевралық сұйықтық немесе пневмоторакс белгілері көрінбейді.",
            "impression": "Жедел патология белгілері анықталмады.",
            "recommendations": "Клиникалық шағымдар сақталса, дәрігерлік бақылау және алдыңғы зерттеулермен салыстыру ұсынылады.",
        },
        FindingClass.pneumonia: {
            "findings": "Өкпе тінінде инфильтративті өзгерістерге сәйкес келуі мүмкін рентгенологиялық белгілер байқалады.",
            "impression": "Пневмония ықтималдығы бар. Клиникалық және зертханалық деректермен салыстыру қажет.",
            "recommendations": "Емдеуші дәрігер бағалауы, қабыну маркерлерімен салыстыру және динамикалық бақылау ұсынылады.",
        },
        FindingClass.pleural_effusion: {
            "findings": "Плевра қуысында сұйықтық болуына күмәнді белгілер байқалады.",
            "impression": "Плевралық сұйықтық ықтимал. Жағы мен көлемін дәрігер сурет бойынша нақтылауы керек.",
            "recommendations": "Клиникалық жағдайға қарай УДЗ/КТ немесе бақылау рентгенографиясы ұсынылады.",
        },
        FindingClass.pneumothorax: {
            "findings": "Пневмотораксқа күмәнді рентгенологиялық белгілер байқалады.",
            "impression": "Пневмоторакс ықтималдығы бар. Шұғыл дәрігерлік бағалау қажет.",
            "recommendations": "Науқастың клиникалық жағдайын дереу бағалап, қажет болса шұғыл көмек алгоритмін қолдану керек.",
        },
        FindingClass.atelectasis: {
            "findings": "Өкпе көлемінің жергілікті төмендеуі немесе ателектазға сәйкес келуі мүмкін белгілер байқалады.",
            "impression": "Ателектаз ықтимал. Дәрігерлік верификация қажет.",
            "recommendations": "Алдыңғы суреттермен салыстыру, клиникалық деректерді бағалау және динамикалық бақылау ұсынылады.",
        },
    },
    "ru": {
        FindingClass.normal: {
            "findings": "Явных признаков острой кардиопульмональной патологии не определяется. Легочные поля без убедительных очагово-инфильтративных изменений, признаков плеврального выпота или пневмоторакса.",
            "impression": "Рентгенологических признаков острой патологии не выявлено.",
            "recommendations": "При сохранении клинических жалоб рекомендуется врачебное наблюдение и сравнение с предыдущими исследованиями.",
        },
        FindingClass.pneumonia: {
            "findings": "Определяются признаки, которые могут соответствовать инфильтративным изменениям в легочной ткани.",
            "impression": "Вероятна пневмония. Требуется сопоставление с клинической картиной и лабораторными данными.",
            "recommendations": "Рекомендована оценка лечащим врачом, корреляция с маркерами воспаления и контроль в динамике.",
        },
        FindingClass.pleural_effusion: {
            "findings": "Определяются признаки, подозрительные на наличие жидкости в плевральной полости.",
            "impression": "Вероятен плевральный выпот. Сторону и объем необходимо уточнить врачом по изображению.",
            "recommendations": "По клиническим показаниям рекомендуется УЗИ/КТ или контрольная рентгенография.",
        },
        FindingClass.pneumothorax: {
            "findings": "Определяются признаки, подозрительные на пневмоторакс.",
            "impression": "Вероятен пневмоторакс. Требуется срочная врачебная оценка.",
            "recommendations": "Необходимо немедленно оценить клиническое состояние пациента и при необходимости действовать по алгоритму неотложной помощи.",
        },
        FindingClass.atelectasis: {
            "findings": "Возможны признаки локального снижения объема легочной ткани или ателектаза.",
            "impression": "Вероятен ателектаз. Требуется врачебная верификация.",
            "recommendations": "Рекомендовано сравнение с предыдущими снимками, оценка клинических данных и контроль в динамике.",
        },
    },
    "en": {
        FindingClass.normal: {
            "findings": "No clear signs of acute cardiopulmonary abnormality are identified. No convincing focal infiltrative change, pleural effusion, or pneumothorax is seen.",
            "impression": "No radiographic signs of acute pathology.",
            "recommendations": "If symptoms persist, clinician follow-up and comparison with prior imaging are recommended.",
        },
        FindingClass.pneumonia: {
            "findings": "Imaging signs may correspond to infiltrative change in the lung parenchyma.",
            "impression": "Pneumonia is possible. Correlation with clinical and laboratory findings is required.",
            "recommendations": "Clinician review, correlation with inflammatory markers, and follow-up imaging as indicated are recommended.",
        },
        FindingClass.pleural_effusion: {
            "findings": "Findings are suspicious for fluid in the pleural space.",
            "impression": "Pleural effusion is possible. Side and volume should be verified by the clinician on the image.",
            "recommendations": "Ultrasound/CT or follow-up radiography may be considered depending on the clinical context.",
        },
        FindingClass.pneumothorax: {
            "findings": "Findings are suspicious for pneumothorax.",
            "impression": "Pneumothorax is possible. Urgent clinician assessment is required.",
            "recommendations": "Assess the patient's clinical condition immediately and follow urgent care protocols if needed.",
        },
        FindingClass.atelectasis: {
            "findings": "There may be signs of focal volume loss or atelectasis.",
            "impression": "Atelectasis is possible. Clinician verification is required.",
            "recommendations": "Comparison with prior imaging, clinical correlation, and follow-up as indicated are recommended.",
        },
    },
}


def _clean_generated_text(value: Any) -> str | None:
    if value is None:
        return None
    if isinstance(value, list):
        text = "\n".join(str(item) for item in value if str(item).strip())
    else:
        text = str(value)
    text = text.strip()
    if not text or text.casefold() in {"none", "null", "n/a", "-"}:
        return None
    text = re.sub(r"```(?:json)?|```", "", text, flags=re.IGNORECASE)
    text = re.sub(r"<unused\d+>|</?s>|<bos>|<eos>", "\n", text, flags=re.IGNORECASE)
    text = re.sub(r"(?i)\bmedgemma\b", "AI", text)
    text = re.sub(r"(?im)^\s*(?:MedAI|AI|local AI)\s+local response\s*:?\s*", "", text)
    text = re.sub(r"(?im)^\s*(?:assistant|user|system)\s*:?\s*", "", text)
    text = re.sub(r"\r\n?", "\n", text)
    lines: list[str] = []
    for raw_line in text.splitlines():
        line = raw_line.strip()
        if not line:
            if lines and lines[-1] != "":
                lines.append("")
            continue
        if re.fullmatch(r"[{}\[\],:\"]+", line):
            continue
        lines.append(line)
    text = "\n".join(lines)
    text = re.sub(r"\n{3,}", "\n\n", text).strip()
    return text or None


def _parse_raw_payload(raw_response_json: str | None) -> dict[str, Any]:
    if not raw_response_json:
        return {}
    try:
        payload = json.loads(raw_response_json)
    except ValueError:
        return {}
    return payload if isinstance(payload, dict) else {}


def _extract_json_payload(text: str | None) -> dict[str, Any]:
    if not text:
        return {}
    decoder = json.JSONDecoder()
    for index, char in enumerate(text):
        if char != "{":
            continue
        try:
            value, _ = decoder.raw_decode(text[index:])
        except json.JSONDecodeError:
            continue
        if isinstance(value, dict):
            return value
    return {}


def _response_section(text: str, headings: tuple[str, ...], stops: tuple[str, ...]) -> str | None:
    for heading in headings:
        pattern = rf"(?:^|\n)\s*{re.escape(heading)}\s*:?\s*"
        match = re.search(pattern, text, flags=re.IGNORECASE)
        if not match:
            continue
        start = match.end()
        end = len(text)
        for stop in stops:
            stop_match = re.search(rf"(?:^|\n)\s*{re.escape(stop)}\s*:?\s*", text[start:], flags=re.IGNORECASE)
            if stop_match:
                end = min(end, start + stop_match.start())
        return _clean_generated_text(text[start:end])
    return None


def _model_generated_sections(analysis: AIAnalysis) -> dict[str, str]:
    payload = _parse_raw_payload(analysis.raw_response_json)
    response = payload.get("response")
    if isinstance(response, dict):
        payload = {**payload, **response}
    elif isinstance(response, str):
        embedded = _extract_json_payload(response)
        if embedded:
            payload = {**embedded, **payload}

    sections: dict[str, str] = {}
    for key in ("findings", "impression", "recommendations"):
        value = _clean_generated_text(payload.get(key))
        if value:
            sections[key] = value

    if sections:
        return sections

    response_text = _clean_generated_text(payload.get("response") or payload.get("raw_generation"))
    if not response_text:
        return {}

    headings = {
        "findings": ("Findings", "Finding", "Description", "Observations"),
        "impression": ("Impression", "Conclusion", "Diagnosis"),
        "recommendations": ("Recommendations", "Recommendation", "Next steps"),
    }
    stop_headings = tuple({item for group in headings.values() for item in group})
    for key, aliases in headings.items():
        value = _response_section(response_text, aliases, tuple(item for item in stop_headings if item not in aliases))
        if value:
            sections[key] = value

    if sections:
        return sections
    return {"findings": response_text}


def _confidence_line(text: dict[str, str], analysis: AIAnalysis) -> str:
    confidence = analysis.confidence or 0
    if confidence > 0:
        return f"{text['confidence']}: {confidence * 100:.1f}%"
    return f"{text['confidence']}: -"


def finding_label(finding: FindingClass | None, lang: str | None) -> str:
    report_lang = normalize_report_lang(lang)
    if not finding:
        return "-"
    return FINDING_LABELS[report_lang].get(finding, finding.value)


def build_localized_ai_draft(study: Study, analysis: AIAnalysis | None, lang: str | None = "ru") -> str:
    report_lang = normalize_report_lang(lang)
    text = TEXT[report_lang]
    lines = [
        text["draft_title"],
        f"{text['study']}: {study.accession_number}",
        f"{text['patient']}: {study.patient_code}",
        f"{text['study_type']}: {study.study_type}",
        "",
    ]
    if study.clinical_note:
        lines.extend([f"{text['clinical_note']}:", study.clinical_note, ""])

    if not analysis or analysis.status.value != "completed":
        lines.extend([text["no_analysis"], text["doctor_review"]])
        return "\n".join(lines)

    generated_sections = _model_generated_sections(analysis)
    if generated_sections:
        if analysis.predicted_class and not analysis.hidden_due_low_confidence:
            lines.append(f"{text['ai_class']}: {finding_label(analysis.predicted_class, report_lang)}")
        lines.append(_confidence_line(text, analysis))
        if analysis.hidden_due_low_confidence or not analysis.predicted_class:
            lines.extend(["", text["low_confidence"]])
        for key in ("findings", "impression", "recommendations"):
            value = generated_sections.get(key)
            if value:
                lines.extend(["", f"{text[key]}:", value])
        lines.extend(["", text["doctor_review"]])
        return "\n".join(lines)

    if analysis.hidden_due_low_confidence or not analysis.predicted_class:
        lines.extend(
            [
                text["low_confidence"],
                _confidence_line(text, analysis),
                text["doctor_review"],
            ]
        )
        return "\n".join(lines)

    template = FINDING_TEXT[report_lang][analysis.predicted_class]
    lines.extend(
        [
            f"{text['ai_class']}: {finding_label(analysis.predicted_class, report_lang)}",
            _confidence_line(text, analysis),
            "",
            f"{text['findings']}:",
            template["findings"],
            "",
            f"{text['impression']}:",
            template["impression"],
            "",
            f"{text['recommendations']}:",
            template["recommendations"],
            "",
            text["model_note"],
            text["doctor_review"],
        ]
    )
    return "\n".join(lines)
